title: Dev Blog
description: idk
theme: just-the-docs

url: https://blog.novastark.com

aux_links:
  Template Repository: https://github.com/just-the-docs/just-the-docs-template

search_enabled: true

search:
  heading_level: 2
  previews: 3
  preview_words_before: 5
  tokenizer_separator: /[\s/]+/
  rel_url: true