title: Dev Blog
description: idk
theme: just-the-docs

url: https://blog.novastark.com

aux_links:
  Main site: https://blog.novastark.com

aux_links_new_tab: true

search_enabled: true

search:
  heading_level: 2
  previews: 3
  preview_words_before: 5
  tokenizer_separator: /[\s/]+/
  rel_url: true

# Footer content
#back_to_top: true
#back_to_top_text: "Back to top"

footer_content: "Copyright and stuff"

# Footer last edited timestamp
last_edit_timestamp: true # show or hide edit time - page must have `last_modified_date` defined in the frontmatter
last_edit_time_format: "%b %e %Y at %I:%M %p" # uses ruby's time format: https://ruby-doc.org/stdlib-2.7.0/libdoc/time/rdoc/Time.html

# Footer "Edit this page on GitHub" link text
gh_edit_link: true # show or hide edit this page link
gh_edit_link_text: "Edit this page on GitHub"
gh_edit_repository: "https://github.com/tentricks/tentricks.github.io" # the github URL for your repo
gh_edit_branch: "main" # the branch that your docs is served from